### ISSUE TITLE
DotExp's substitution method is broken

### ISSUE THREAD

**Issue by yushan87** [ClemsonRSRG/RESOLVE#325]
Suppose our `DotExp` was `A.Foo` and the substitution map that got passed to us contained `Foo` -> `Bar` and `A.Foo` to `A.B.Foo`. In this case, we don't want to apply the substitution and get `A.Bar`. The right result should be `A.B.Foo`. 

What I think we should do is substitute using the key that matches the most segments. 
**Examples:** [Our map contains: `S` -> `T`, `S.A` -> `S.B`, `A.B` -> `A`].
1. `S.Top` will become `T.Top`.
2. `S.A.Top` will become `S.B.Top`.
3. `A.B.Top` will become `A.Top`.
4. `S.A.B.Top` will become `S.B.Top`.

@dtwelch What are your thoughts on this?

**Comment by dtwelch** [comment]
Yeah, that seems right.
